
import React from 'react'
import Head from 'next/head'
import Logo from '@/components/Logo'
import Hero from '@/components/Hero'




const index = () => {

  return (
    <>
      <Head>
        <title>Scam Checker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo/>
      <Hero heading="Website safety checker" message="Check the safety of a website"/>
      
    </>
  )
}

export default index